name: search-stop-words
on: [push]
jobs:
  search-stop-words:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - name: clone go-automation
        run: git clone https://github.com/Yandex-Practicum/go-automation.git /tmp/go-automation
      - name: install yt-stop-word-searcher
        run: cd /tmp/go-automation/tools/yt-stop-word-searcher && go install .
      - name: find stop words
        run: yt-stop-word-searcher -root=./lessons
