name: validate-snippet-comments
on: [push]
jobs:
  validate-snippet-format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - name: clone go-automation
        run: git clone https://github.com/Yandex-Practicum/go-automation.git /tmp/go-automation
      - name: install yt-comment-validator
        run: cd /tmp/go-automation/tools/yt-comment-validator && go install .
      - name: validate snippet format
        run: yt-comment-validator -root=./lessons
